version: "3.4"

networks:
  besu-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

services:

  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - type: bind
        source: /Volumes/SEGATE-LIVE/besu-test/main/prometheus
        target: /prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      besu-network:
        ipv4_address: 172.16.1.2

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    
    networks:
      besu-network:
        ipv4_address: 172.16.1.3

  bootnode:
    container_name: bootnode
    image: hyperledger/besu:20.10.0
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu --data-path=/var/lib/besu \
        --genesis-file=/opt/besu/genesis.json --rpc-http-enabled \
        --host-allowlist="*" --rpc-http-cors-origins="all" \
        --metrics-enabled \
        --rpc-http-api=ETH,NET,IBFT;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node1/data:/opt/besu/data
      - type: bind
        source: /Volumes/SEGATE-LIVE/besu-test/main/node1
        target: /var/lib/besu
    ports:
      - 8545:8545
      - 30303:30303
      - 9545:9454
    networks:
      besu-network:
        ipv4_address: 172.16.1.30
  
  node2:
    container_name: node2
    image: hyperledger/besu:20.10.0

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/var/lib/besu \
         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled \
         --host-allowlist="*" --rpc-http-cors-origins="all" \
         --metrics-enabled \
         --bootnodes=enode://504a6fff2c82ee930e7ec15564732e91e1760f1ce319bf5073cc0190d8a11a504eb81714fe036bbddf0c380925abcf09635a980d3d6d5d086594add972db5280@172.16.1.30:30303 --p2p-port=30304;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node2/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
      - type: bind
        source: /Volumes/SEGATE-LIVE/besu-test/main/node2
        target: /var/lib/besu
    ports:
      - 8546:8545
      - 30304:30303
      - 9546:9454
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.1.31
  
  node3:
    container_name: node3
    image: hyperledger/besu:20.10.0

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/var/lib/besu \
         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled \
         --host-allowlist="*" --rpc-http-cors-origins="all" \
         --metrics-enabled \
         --bootnodes=enode://504a6fff2c82ee930e7ec15564732e91e1760f1ce319bf5073cc0190d8a11a504eb81714fe036bbddf0c380925abcf09635a980d3d6d5d086594add972db5280@172.16.1.30:30303 --p2p-port=30305;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node2/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
      - type: bind
        source: /Volumes/SEGATE-LIVE/besu-test/main/node3
        target: /var/lib/besu
    ports:
      - 8547:8545
      - 30305:30306
      - 9547:9454
    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.1.33
  
  node4:
    container_name: node4
    image: hyperledger/besu:20.10.0

    entrypoint:
      - /bin/bash
      - -c
      - |
        sleep 10;
        /opt/besu/bin/besu --data-path=/var/lib/besu \
         --genesis-file=/opt/besu/genesis.json --rpc-http-enabled \
         --host-allowlist="*" --rpc-http-cors-origins="all" \
         --metrics-enabled \
         --bootnodes=enode://504a6fff2c82ee930e7ec15564732e91e1760f1ce319bf5073cc0190d8a11a504eb81714fe036bbddf0c380925abcf09635a980d3d6d5d086594add972db5280@172.16.1.30:30303 --p2p-port=30306;

    volumes:
      - ./genesis.json:/opt/besu/genesis.json
      - ./node2/data:/opt/besu/data
      - ./log-config.xml:/config/log-config.xml
      - type: bind
        source: /Volumes/SEGATE-LIVE/besu-test/main/node4
        target: /var/lib/besu
    ports:
      - 8548:8545
      - 30306:30303
      - 9548:9454

    depends_on:
      - bootnode
    networks:
      besu-network:
        ipv4_address: 172.16.1.34